// Generated by https://quicktype.io

export interface ICertificate {
  id: string;
  time_elapsed: number;
  platform: string;
  graduated: Graduated;
  description: string;
  title: string;
  imageUrl: string;
}

export interface Graduated {
  seconds: number;
  nanoseconds: number;
}
